kind: live
title: private-gpt

# other files from https://github.com/zylon-ai/private-gpt

defaults:
  life_span: 5d
  env:
    VLLM_MODEL: deepseek-ai/DeepSeek-R1-Distill-Qwen-32B # used in pgpt, vllm
    VLLM_TOKENIZER: deepseek-ai/DeepSeek-R1-Distill-Qwen-32B # used in pgpt, vllm
    VLLM_CONTEXT_WINDOW: 34960 # used in pgpt, vllm
    EMBEDDING_MODEL: nomic-ai/nomic-embed-text-v1.5 # used in pgpt, tei

images:
  privategpt:
    ref: image:$[[ project.id ]]:v1
    dockerfile: $[[ flow.workspace ]]/Dockerfile.apolo
    context: $[[ flow.workspace ]]/
    build_preset: cpu-large
    extra_kaniko_args: --compressed-caching=false

volumes:
  cache:
    remote: storage:$[[ flow.project_id ]]/cache
    mount: /root/.cache/huggingface
    local: cache
  data:
    remote: storage:$[[ flow.project_id ]]/data
    mount: /home/worker/app/local_data
    local: local_data
  pgdata:
    remote: storage:$[[ flow.project_id ]]/pgdata
    mount: /var/lib/postgresql/data
    local: pgdata
  settings:
    remote: storage:$[[ flow.project_id ]]/settings
    mount: /home/worker/app/settings
    local: settings
  tiktoken_cache:
    remote: storage:$[[ flow.project_id ]]/tiktoken_cache
    mount: /home/worker/app/tiktoken_cache
    local: tiktoken_cache

jobs:
  pgpt:
    image: ${{ images.privategpt.ref }}
    name: pgpt
    preset: cpu-small
    http_port: "8080"
    detach: true
    browse: true
    volumes:
      - ${{ volumes.data.ref_rw }}
      - ${{ upload(volumes.settings).ref_rw }}
      - ${{ volumes.tiktoken_cache.ref_rw }}
    env:
      PORT: 8080
      PGPT_PROFILES: app, pgvector
      PGPT_SETTINGS_FOLDER: ${{ volumes.settings.mount }}
      VLLM_API_BASE: http://${{ inspect_job('vllm').internal_hostname_named }}:8000/v1
      EMBEDDING_API_BASE: http://${{ inspect_job('tei').internal_hostname_named }}:3000/v1
      POSTGRES_HOST: ${{ inspect_job('pgvector').internal_hostname_named }}
      HUGGINGFACE_TOKEN: secret:HF_TOKEN
      HF_HOME: /home/worker/app/models/cache

  vllm:
    image: vllm/vllm-openai:v0.6.6.post1
    preset: a100x1
    detach: true
    volumes:
      - ${{ volumes.cache.ref_rw }}
    env:
      HF_TOKEN: secret:HF_TOKEN
    cmd: >
      --model $(VLLM_MODEL)
      --tokenizer $(VLLM_TOKENIZER)
      --dtype=half
      --trust-remote-code
      --max-model-len $(VLLM_CONTEXT_WINDOW)

  tei:
    image: ghcr.io/huggingface/text-embeddings-inference:1.2.3
    preset: a100x1
    detach: true
    volumes:
      - ${{ volumes.cache.ref_rw }}
    env:
      HUGGING_FACE_HUB_TOKEN: secret:HF_TOKEN
    cmd: >
      --hostname=0.0.0.0 --port=3000 --model-id=$(EMBEDDING_MODEL) --max-client-batch-size=100

  pgvector:
    image: pgvector/pgvector:pg16
    detach: true
    preset: cpu-small
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: ${{ volumes.pgdata.mount }}/pgdata
    volumes:
      # If PGVector cannot start because of filesystem locks, try using Apolo Disks instead of Storage
      - ${{ volumes.pgdata.ref_rw }}
